# Generated by Django 2.2.24 on 2021-07-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.Maestro')),
            ],
        ),
    ]
